### ISSUE TITLE
Module cannot be resolved when building with Parcel

### ISSUE THREAD

**Issue by joneubank** [Ameobea/react-control-panel#35]
I am unable to include this module in projects when building with [Parcel Bundler](https://parceljs.org/) since upgrading to version 2. The root of the problem is the `module` property in the `package.json` points to a `/lib` directory that is not included in the NPM published module and this is being prioritized over `main` to find the built code.

`package.json` declares these properties:
```
  "main": "dist/index.js",
  "module": "./lib/index.js",
```
Is there a reason for the `/lib` path here? Maybe this is something you use locally or an old configuration that is no longer needed?

There are two possible changes that would resolve this issue:
1. removing the `module` property
or
2. updating it to be `"module": "./dist/index.js"` would both fix the build issue.

PS. thanks for this library, its worked really nicely for me for a while now. Nice shortcut to get some UI controls going with some styling that I quite like.

**Comment by Ameobea** [comment]
Very sorry for the big delay in fixing this, and thank you @joneubank for the detailed report.  I had notifications messed up for this repo.

This has been fixed and is released in version 0.9.1
